---
title: Share reports
format: html
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = TRUE)

# Load your packages here

```

## Create your report here

We've included code combining elements from Milestone 9 to help you get started. You may wish to delete this code or copy over code from other milestones as well.


```{r}
#| label: import
#| message: false
library(tidyverse)
library(gt)

mdrd <- read_csv("data/mdrd.csv")
supp <- read_csv("data/supp.csv")
```

```{r}
#| label: mdrd-tidy
#| message: false
mdrd_tidy <- mdrd %>%
  filter(dropout == 0) %>% 
  pivot_longer(
    cols = starts_with("diet"),
    names_to = "treatment",
    values_to = "value"
  ) %>%
  filter(value == 1) %>%
  separate(
    col = treatment,
    into = c("diet", "bp"),
    sep = "_"
  ) %>%
  mutate(
    diet = str_remove(diet, "^diet"),
    bp = str_remove(bp, "bp$")
  ) %>%
  mutate(
    diet = if_else(diet == "k", "very low-protein", "low-protein"),
    bp = if_else(bp == "norm", "normal", bp)
  ) %>%
  group_by(diet, bp, ptid) %>%
  summarize(
    gfr_slope = (last(gfr, order_by = months) - first(gfr, order_by = months)) / max(months),
  ) %>%
  filter(!is.nan(gfr_slope)) %>%
  ungroup() 

mdrd_tidy
```

```{r}
#| label: mdrd-summary
#| message: false
mdrd_summary <- 
  mdrd_tidy %>%
  group_by(diet, bp) %>%
  summarize(
    n_patients = n(),
    mean_gfr_slope = mean(gfr_slope)
  ) %>% 
  ungroup()

mdrd_summary
```

```{r}
#| label: mdrd-table
mdrd_table <- 
  mdrd_summary %>% 
  gt() %>% 
  cols_label(
    diet = "Diet",
    bp = "BP",
    n_patients = "n",
    mean_gfr_slope = "Mean GFR slope"
  ) %>% 
  tab_header(
    title = "Mean change in GFR over time",
    subtitle = "By treatment group"
  ) %>% 
  fmt_number(
    columns = "mean_gfr_slope",
    decimals = 2
  ) %>% 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = cells_body(columns = c(diet, bp))
  ) %>% 
  tab_source_note(
    source_note = "Source: NIDDK"
  )

mdrd_table
```

```{r}
#| label: mdrd-tidy-plot
mdrd_tidy %>%  
  ggplot(aes(x = bp, y = gfr_slope, fill = bp)) + 
  geom_boxplot() +
  scale_fill_brewer(palette = "Set2") +
  facet_grid(cols = vars(diet)) +
  theme_light() +
  labs(
    title = "Change in glomerular filtration rate (GFR) across four treatment groups",
    x = "Blood pressure",
    y = "GFR slope",
    caption = "Source: NIDDK"
  ) +
  theme(legend.position = "none")
```

