---
title: "Standardize events"
output: html_document
date: "2025-10-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(tidyverse)
library(arrow)


source('dev_parnel_parse_events.R')
source('functions/fxn_event_type.R')
source('functions/fxn_parse_free_text.R')
```


```{r}
df<-read_parquet('data/template_files/mySYNCH_outreach_event_details.parquet')%>%
  filter(!(is.na(Event)))%>%
  filter(!(str_detect(Event, '\\d\\d_\\d\\d_\\d\\d')))%>%
  mutate(event = Event)%>%
  mutate(
    remark = case_when(
      is.na(Remark) ~ 'missing', 
      TRUE~Remark), 
    protocols = case_when(
      is.na(Protocols)~'missing', 
      TRUE~Protocols)
    )%>%
  fxn_assign_event_type_default()%>%
   filter(event_type %in% c('health', 'unknown'))%>%
    fxn_parse_remark_default()%>%
    fxn_parse_protocols_default()
 

```

## events by type

```{r}

df2<-df%>%
  group_by(event_type, event)%>%
  summarize(ct_rows = sum(ct_rows), 
            #list_remarks = paste0(sort(unique(remark)), collapse = ','),
            list_protocols = paste0(sort(unique(protocols)), collapse = ',')
            )%>%
  ungroup()%>%
  filter(event_type %in% 'unknown')%>%
  arrange(desc(ct_rows))

```


