---
title: "Untitled"
format: html
date: "`r Sys.Date()`"
embed-resources: true
---


```{r}
library(tidyverse)
library(quarto)
library(arrow)

#Create denominator files by year
quarto::quarto_render(
  input = "step3_denominators_by_lactation_group.qmd",
  execute_params = list(
    denominator_granularity = 365,
      cut_by_days = 30,
      top_cut = 400,
      top_cut_hfr = 500
  )
)


#Create denominator files by month
quarto::quarto_render(
  input = "step3_denominators_by_lactation_group.qmd",
  execute_params = list(
    denominator_granularity = 30,
      cut_by_days = 30,
      top_cut = 400,
      top_cut_hfr = 500
  )
)
```
## lact group

```{r}
get_deno_files<-tibble(file_names = list.files('data/intermediate_files'))%>%
  filter(str_detect(file_names, 'denominator_by_lact_group'))
                         
herd_deno_new = read_parquet('data/intermediate_files/denominator_by_lact_group_time_period365.parquet')%>%
  filter(date_time_period_start>(today()-1200))%>%
  filter(!(deno_type %in% c("dop_lact_basic", "dop_lact_2+", "dop_lact_3+", "dop_lact_5+",'lact_2+')))

herd_deno_new_long<-herd_deno_new%>%
  pivot_longer(cols = c('ct_animal_lactations', 'ct_animals', 'ct_animal_time_periods'), 
               names_to = 'metric', 
               values_to = 'ct' )
```

## Monthly

```{r}
#monthly -------------------------------------
herd_deno_monthly_new = read_parquet('data/intermediate_files/denominator_by_lact_group_time_period30.parquet')%>%
  filter(date_time_period_start>(today()-1200))%>%
  filter(!(deno_type %in% c("dop_lact_basic", "dop_lact_2+", "dop_lact_3+", "dop_lact_5+",'lact_2+')))

herd_deno_monthly_new_long<-herd_deno_monthly_new%>%
  pivot_longer(cols = c('ct_animal_lactations', 'ct_animals', 'ct_animal_time_periods'), 
               names_to = 'metric', 
               values_to = 'ct' )
```

## Dim Categories

```{r}
#dim cats-----------------------------------
herd_deno_dim_new = read_parquet('data/intermediate_files/denominator_by_lact_group_time_period365.parquet')%>%
  filter(date_time_period_start>(today()-1200))%>%
  filter((deno_type %in% c("dop_lact_basic", 'dop_lact_3+', 'dop_lact_5+')))

herd_deno_dim_new_long<-herd_deno_dim_new%>%
  pivot_longer(cols = c('ct_animal_lactations', 'ct_animals', 'ct_animal_time_periods'), 
               names_to = 'metric', 
               values_to = 'ct' )

```




## Compare to step3_create_denominators_lact_dim_season

### Lactation Group Counts

```{r}
herd_deno<-read_parquet('data/intermediate_files/herd_denominators.parquet')%>%
  mutate(date = lubridate::ymd(paste0(time_period, '-01-01')))


```


#### plot lact group counts

```{r}
ggplot()+
  geom_point(data = herd_deno,
             aes(x = date, y = count_lactations), color = 'blue', shape = 15, size = 2)+
  geom_point(data = herd_deno,
             aes(x = date, y = count_animals), color = 'black', shape = 15, sie = 2)+
  geom_point(data = herd_deno_new_long,
             aes(x = date_time_period_start, y = ct, color = metric))+
  
  facet_grid(location_lact_list~`Lactation Group`, scales = 'free_y')+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        legend.position = 'top')+
  labs(fill = '', 
       title = 'Denominator Options',
      subtitle = 'Square = Old, Circle = New')+
  scale_color_manual(values = c('ct_animal_lactations' = 'blue', 
                                'ct_animals' = 'black', 
                                'ct_animal_time_periods' = 'red'))
```


## Dim Categories

### plot dim cats

```{r}
herd_deno_dim<-read_parquet('data/intermediate_files/herd_dim_denominators.parquet')%>%
  mutate(date = lubridate::ymd(paste0(time_period, '-01-01')))

ggplot()+
  geom_point(data = herd_deno_dim,
             aes(x = date, y = `count`), color = 'blue', shape = 15)+
  # geom_point(data = herd_deno_dim,
  #            aes(x = date, y = count_animals), color = 'black', shape = 15)+
  geom_point(data = herd_deno_dim_new_long,
             aes(x = date_time_period_start, y = ct, color = metric))+
  
  facet_grid(location_lact_list~`Lactation Group`, scales = 'free_y')+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        legend.position = 'top')+
  labs(fill = '', 
       title = 'Denominator Options', 
       subtitle = 'Square = Old, Circle = New')+
  scale_color_manual(values = c('ct_animal_lactations' = 'blue', 
                                'ct_animals' = 'black', 
                                'ct_animal_time_periods' = 'red'))
```

## Monthly

### plot monthly
```{r}
herd_deno_monthly<-read_parquet('data/intermediate_files/herd_season_denominators.parquet')%>%
  mutate(date = lubridate::my(month))

ggplot()+
  geom_point(data = herd_deno_monthly,
             aes(x = date, y = `count`), color = 'blue', shape = 15)+
  # geom_point(data = herd_deno_dim,
  #            aes(x = date, y = count_animals), color = 'black', shape = 15)+
  geom_point(data = herd_deno_monthly_new_long,
             aes(x = date_time_period_start, y = ct, color = metric), alpha = .1)+
  
  facet_grid(location_lact_list~`Lactation Group`, scales = 'free_y')+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1), 
        legend.position = 'top')+
  labs(fill = '', 
       title = 'Denominator Options', 
       subtitle = 'Square = Old, Circle = New')+
scale_color_manual(values = c('ct_animal_lactations' = 'blue', 
                                'ct_animals' = 'black', 
                                'ct_animal_time_periods' = 'red'))

```



