---
title: Read and Visualize
date: "`r Sys.Date()`"
embed-resources: true

---

```{r include = FALSE}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = TRUE)

# This chunck is already finished for you, you don't need to modify anything here
library(tidyverse) #this includes many packages and is the main package used in nearly all data wrangling
library(arrow) #this package handles parquet files

#add some extra functions
source('../milestones_dairy/data_milestones/fxn_floor_dates.R')

```

## Get data

```{r}

events_formatted<-read_parquet('../data/intermediate_files/events_formatted.parquet')%>%
  add_new_variables()%>%
  filter(event %in% 'BRED1')

heifers<-events_formatted%>%
  filter(lact_number == 0)%>%
  mutate(group = 'heifers')

cows<-events_formatted%>%
  filter(lact_number > 0)%>%
  mutate(group = 'cows')


```


## Create scaling factor


```{r}
scale_factor <-   median(cows$dim_event)/median(heifers$dim_event)

final_data<-bind_rows(
  cows %>% mutate(dim_event_scaled = dim_event),
  heifers %>% mutate(dim_event_scaled = dim_event * scale_factor)
)
```

## Plot

```{r}
ggplot(final_data, aes(x = floordate_month)) +
  geom_point(aes(y = dim_event_scaled, color = group)) +
  geom_smooth(aes(y = dim_event_scaled, color = group), se = FALSE) +
  scale_y_continuous(
    name = "Cows",
    sec.axis = sec_axis(~ . / scale_factor, name = "Heifers")
  ) +
  scale_color_manual(values = c("cows" = "blue", "heifers" = "red")) +
  theme_minimal()


```

## Example of coord_cartesian to "zoom in"

```{r}

 ggplot(final_data, aes(x = floordate_month)) +
  geom_point(aes(y = dim_event_scaled, color = group), size = 0.2, alpha = .2) +
  geom_smooth(aes(y = dim_event_scaled, color = group, fill = group), alpha = .2) +
  scale_y_continuous(
    name = "Cows",
    sec.axis = sec_axis(~ . / scale_factor, name = "Heifers")
  ) +
  scale_color_manual(values = c("cows" = "blue", "heifers" = "red")) +
  scale_fill_manual(values = c("cows" = "blue", "heifers" = "red")) +
  theme_minimal()+
  coord_cartesian(ylim = c(50, 100))

```



