---
title: "Sample Lameness Report"
editor: source
format: 
 html:
   embed-resources: true
   toc: true
   toc-location: left
   code-fold: true
execute:
    echo: false
    message: false
    warning: false
params:
  herd: 
  year: 2025
---

```{r}
#| label: setup

if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  broom,
  tidyverse,
  dtplyr,
  gt,
  arrow,
  rmarkdown,
  lubridate,
  quarto, 
  arrow,
  survival,
  survminer,
  ggsurvfit,
  flextable,
  gtsummary,
  marginaleffects,
  scales,
  here,
  zoo
  )

source(here::here('functions/fxn_dt_base.R')) #functions to parse remarks and protocols

# load GC's lame functions
source(here::here('functions/fxn_load_os_fxns.R'))
fxn_load_os_fxns()

animals <-read_parquet(here::here('data/intermediate_files/animals.parquet')) 

events_formatted <- read_parquet(here::here('data/intermediate_files/events_formatted.parquet')) |> 
     filter(event %in% c("LAME", "FOOTRIM", "TRIM")) 


date_max_pull <- max(events_formatted$date_event)
farm_name <- unique(events_formatted$location_event)


# denominator stuff
year_filter <- make_date(params$year, 1, 1)

deno_cal <- read_parquet(here::here(
  'data/intermediate_files/denominator_by_calendar_time_period.parquet')) |> 
  filter(deno_type %in% c("lact_basic", "lact_3+") & 
           calendar_time_period_type == "year") |> 
  select(-c(contains("dop"), day_of_phase_group)) |> 
  filter(date_time_period_start >= year_filter & date_time_period_start < year_filter + years(1))

```


```{r}
#| label: summary data

summarize_events<-events_formatted |> 
  group_by(farm = location_event, event, protocols_remaining_after_numbers1, 
           remark_letters1
           ) |> 
  summarize(count_rows=sum(n()))|>
  ungroup()%>%
  mutate(event_type = factor(protocols_remaining_after_numbers1), 
         remark_type = factor(remark_letters1), 
         Event = factor(event),
         event_type = if_else(is.na(event_type),
                              "No Protocol Recorded", event_type),
         remark_type = if_else(is.na(remark_type), "No Remark Recorded",
                               remark_type)
         )

```

## Check out what Lesions are being reported

### Protocol Data

```{r}
#| fig-height: 12
# count y vars

facet_order <- summarize_events %>%
  group_by(farm, event_type) %>%
  summarise(n_y = n_distinct(event)) %>%
  arrange(desc(n_y)) %>%  # Order by most y categories
  pull(event_type)

# order events
summarize_events <- summarize_events %>%
  mutate(event_type = fct_reorder(event_type, count_rows, .fun = sum, .desc = FALSE)) 

  ggplot(summarize_events)+
  geom_bar(aes(x = event_type,
               y = count_rows, fill = event_type), stat = "identity")+
  #facet_wrap(factor(event, levels = facet_order) ~., scales = 'free')+
    facet_wrap(vars(farm, event), ncol = 2 , scales = "free")+
  coord_flip()+
  scale_fill_viridis_d()+
  theme_minimal()+
  labs(x = "",
       y = "Row Count")+
  theme(legend.position = "none",
        # axis.text.y = element_text(size = 6)
        )
```

### Remarks

Description of top 10 remarks recorded, Other is combined remaining remarks

```{r}
#| fig-height: 8

facet_order <- summarize_events %>%
  group_by(farm, remark_type) %>%
  summarise(n_y = n_distinct(event)) %>%
  arrange(desc(n_y)) %>%  # Order by most y categories
  pull(remark_type)

# order events
summarize_events <- summarize_events %>%
  # mutate(event_type = fct_reorder(remark_type, 
  #                                 count_rows, .fun = sum, .desc = FALSE)) 
  mutate(remark_type = fct_lump_n(remark_type,
                                 n = 10,
                                 ties.method = "random" ))
  

  ggplot(summarize_events)+
  geom_bar(aes(x = remark_type,
               y = count_rows, fill = remark_type), stat = "identity")+
  #facet_wrap(factor(event, levels = facet_order) ~., scales = 'free')+
    facet_wrap(vars(farm, event), ncol = 2, scales = "free")+
  coord_flip()+
  scale_fill_viridis_d()+
  theme_minimal()+
  labs(x = "",
       y = "Row Count")+
  theme(legend.position = "none",
        # axis.text.y = element_text(size = 6)
        )
  
```




```{r}
#| label: process_data

# assign lesion

# assign lesion variables 

all_lesions <- c("dd", "footrot", 'wld', "sole_ulcer","injury", 
                             "cork", "other", "hemorrhage",
                             "sole_fracture", "toe_ulcer", "thin",
                             "inf", "noninf", "toe", "axial", "lesion")

# for chroncity stuff
diseases <- c("inf", "noninf", "lesion")


lame_data <- events_formatted |> 
  select(id_animal, date_birth, date_fresh,lact_number, lact_group, 
         date_archived, date_event, event, 
         remark_letters1, protocols_letters1, location_event) |> 
  filter(event %in% c("LAME", "TRIM", "FOOTRIM")) |>
  fxn_code_lesions(protocol_var = protocols_letters1,
                  remark_var = remark_letters1) |> 
  # fix ab and NA issues
  filter(!is.na(trimonly)) |>
  mutate(noninf = case_when(
    other == 1 & str_detect(protocols_letters1, "Ab") ~ 1,
    .default = noninf),
    # remove other catergory if abscess is found
    other = case_when(
      other == 1 & str_detect(protocols_letters1, "Ab") ~ 0,
      .default = other)
    ) |> 
  fxn_collapse_lesions(lesions = all_lesions) |> 
  fxn_trim_vars(location_event, id_animal,
                date_var = date_event,
                trimonly_var = trimonly) |> 
  fxn_dz_status(disease_cols = diseases,
                event_filter = trimonly == 0) |> 
# join with animals to get left date
  left_join(animals |> 
              select(id_animal, date_sold, date_died, date_left),
            by = "id_animal") |> 
# add cull data
  mutate(
    # create culling variables
    culled_ever = if_else(is.na(date_left), 0, 1),
    days_to_cull = date_left - date_event,
    # temp censor date need to adjust
    date_censor = ymd(date_max_pull) 
  ) |> 
  mutate(days_to_censor_cull = case_when(culled_ever == 1 ~
                                     days_to_cull,
                                    # cows not culled
                                    culled_ever == 0 ~
                                      date_censor - 
                                                    date_event,
                                    .default =  NA
                                    ),
    across(starts_with("days"), as.numeric)
    ) |> 
  group_by(location_event, id_animal) |> 
  mutate(culled_last_trim = 
           if_else(culled_ever == 1 & !is.na(days_to_next_trim), 0, 
                   culled_ever),
         culled_30 = if_else(culled_ever == 1 & 
                               days_to_cull <=30, 1, 0
                             )
         )|>
  ungroup() |> 
  select(location_event, id_animal, date_birth, lact_number, lact_group,
         date_event,
         date_left, date_died, date_sold,
         #lesion, inf, noninf,
         any_of(all_lesions),
         trimonly, times_trimmed, date_censor, 
         days_to_cull, days_to_censor_cull,culled_ever, culled_last_trim,
         culled_30, date_prev_trim, days_to_next_trim, 
         starts_with("life_"), starts_with("status_")
         )


```

```{r}
#| label: lesion-categories

# 1. Define which lesions fall into each category
infectious_lesions <- c("dd", "footrot")

non_infectious_lesions <- c(
  "wld", "sole_ulcer", "hemorrhage", 
  "sole_fracture", "toe_ulcer", 
  "thin", "cork", "injury")

  # labels for plot
  lesion_labels <- c(
    "Digital Dermatitis"  = "dd",
    "Footrot"             = "footrot",
    "White Line Disease" = "wld",
    "Sole Ulcer" = "sole_ulcer",
    "Hemorrhage" = "hemorrhage",
    "Sole Fracture" = "sole_fracture",
    "Toe Ulcer" = "toe_ulcer",
    "Thin Soles" = "thin",
    "Corkscrew Claw " = "cork",
    "Injury" = "injury",
    "Any Lesion" = "lesion",
    "Infectious" = "inf",
    "Non-Infectious" = "noninf",
    "Other Lesions" = "other"
  )
  
all_lesions_label <- c(infectious_lesions, non_infectious_lesions)

```



```{r}
#| label: count lesions

inventory <- deno_cal |> 
  mutate(year = year(date_time_period_start)) |> 
  filter(year == params$year) |>
  # pick just milking cows
  filter(`Lactation Group` == "LACT > 0") |>
  select(location_lact_list, year, ct_animal_time_periods, 
         'Lactation Group') |> 
  mutate(ct_animal_time_periods = round(ct_animal_time_periods, 0))
  

base_lesion_data <- lame_data |>
  mutate(year = year(date_event)) |>
    filter(year == params$year) |>
    pivot_longer(
    cols = all_of(all_lesions),
    names_to = "lesion_type",
    values_to = "has_lesion"
  ) |>
  filter(has_lesion == 1) |>
  mutate(
    lesion_group = if_else(lesion_type %in% infectious_lesions,
                           "Infectious Lesions", "Non-Infectious Lesions")
  ) |>
  count(location_event, year,
        lesion_group, lesion_type, status_lesion,
        name = "lesion_count") |>
  left_join(inventory, by = join_by(location_event == location_lact_list,
                                           year)) |> 
  mutate(incidence_rate = (lesion_count / ct_animal_time_periods) * 100
  )

# Create 2 specific data subsets
inf_data <- base_lesion_data |>
  filter(lesion_group == "Infectious Lesions")

noninf_data <- base_lesion_data |>
  filter(lesion_group == "Non-Infectious Lesions")


```

```{r}
#| label: count lesions lact

inventory_3 <- deno_cal |> 
  mutate(year = year(date_time_period_start)) |> 
    filter(year == params$year) |>
  # pick just milking cows
  filter(deno_type == "lact_3+" & `Lactation Group` != "Heifer") |>
  select(location_lact_list, year, ct_animal_time_periods, 
         'Lactation Group') |> 
  mutate(ct_animal_time_periods = round(ct_animal_time_periods, 0))
  

base_lesion_data_3 <- lame_data |>
  mutate(year = year(date_event)) |>
    filter(year == params$year) |>
  filter(lact_number >0) |> 
    pivot_longer(
    cols = all_of(all_lesions),
    names_to = "lesion_type",
    values_to = "has_lesion"
  ) |>
  filter(has_lesion == 1) |>
  mutate(
    lesion_group = if_else(lesion_type %in% infectious_lesions,
                           "Infectious Lesions", "Non-Infectious Lesions")
  ) |>
  count(location_event, year, lact_group,
        lesion_group, lesion_type, status_lesion,
        name = "lesion_count") |>
  left_join(inventory_3, by = join_by(location_event == location_lact_list,
                                      lact_group == `Lactation Group`,
                                      year)) |> 
  mutate(incidence_rate = (lesion_count / ct_animal_time_periods) * 100
  )

# Create 2 specific data subsets
inf_data_3 <- base_lesion_data_3 |>
  filter(lesion_group == "Infectious Lesions")

noninf_data_3 <- base_lesion_data_3 |>
  filter(lesion_group == "Non-Infectious Lesions")


```


```{r}
#| label: graph function

plot_lollipop <- function(.data,
                          x_var = incidence_rate,
                          y_var = location_event, ...) {
  .data |>
    ggplot() +
    geom_segment(
      aes(
        x = {{ x_var }}, xend = 0,
        y = {{ y_var }}, yend = {{ y_var }},
        color = {{ y_var }}
      ),
      linewidth = 2
    ) +
    geom_point(
      aes(
        x = {{ x_var }}, y = {{ y_var }},
        color = {{ y_var }}
      ),
      size = 8
    ) +
    scale_color_viridis_d() +
    # adds some white space around edges so points not cut off
    scale_x_continuous(expand = expansion(mult = (c(.1, .1)))) +
    scale_y_discrete(expand = expansion(add = 1))
}


```

# Lesion Incidence for `r params$year`

::: panel-tabset
## Summary Categories

```{r}
#| label: graph all lesions

les_graph <- base_lesion_data |> 
  filter(lesion_type %in% c("lesion", "inf", "noninf", "other")
         ) |>
  mutate(lesion_type = fct_reorder(lesion_type, incidence_rate)
         )|>
  mutate(lesion_type = fct_recode(lesion_type, !!!lesion_labels)) |> 
    mutate(lesion_type = fct_recode(lesion_type, !!!lesion_labels),
         status_lesion = fct_relevel(status_lesion, c("New", "Repeat", "Chronic"))
         ) |>
  plot_lollipop(y_var = lesion_type)+
  geom_text(aes(x = incidence_rate, y = lesion_type,
                label = round(incidence_rate, 1)),
            nudge_x = +.01, color = "white", size = 3)+
  facet_grid(
    cols = vars(location_event),
    rows = vars(status_lesion),
  )+
  theme_minimal()+
  guides(color = "none")+
  labs(x = "Cases per 100 Cows", y = NULL)

les_graph

```

## Individual Lesions


```{r}
#| label: graph individual lesions

les_graph <- base_lesion_data |> 
  filter(lesion_type %in% (all_lesions_label)
         ) |>
  mutate(lesion_type = fct_reorder(lesion_type, incidence_rate)
         )|>
  mutate(lesion_type = fct_recode(lesion_type, !!!lesion_labels),
         status_lesion = fct_relevel(status_lesion, c("New", "Repeat", "Chronic"))
         ) |>
  plot_lollipop(y_var = lesion_type)+
  geom_text(aes(x = incidence_rate, y = lesion_type,
                label = round(incidence_rate, 1)),
            nudge_x = +.01, color = "white", size = 3)+
  facet_grid(
    cols = vars(location_event),
    rows = vars(status_lesion),
  )+
  theme_minimal()+
  guides(color = "none")+
  labs(x = "Cases per 100 Cows", y = NULL)

les_graph

```
## Lactation

```{r}
#| label: graph individual lesions lact

les_graph <- base_lesion_data_3 |> 
  filter(lesion_type %in% (all_lesions_label)
         ) |>
  mutate(lesion_type = fct_reorder(lesion_type, incidence_rate)
         )|>
    mutate(lesion_type = fct_recode(lesion_type, !!!lesion_labels),
         status_lesion = fct_relevel(status_lesion, c("New", "Repeat", "Chronic"))
         ) |> 
  mutate(lesion_type = fct_recode(lesion_type, !!!lesion_labels)) |> 
  plot_lollipop(y_var = lesion_type)+
  geom_text(aes(x = incidence_rate, y = lesion_type,
                label = round(incidence_rate, 1)),
            nudge_x = +.01, color = "white", size = 3)+
  facet_grid(
    cols = vars(lact_group),
    rows = vars(status_lesion),
  )+
  theme_minimal()+
  guides(color = "none")+
  labs(x = "Cases per 100 Cows", y = NULL)

les_graph

```



:::

# Time to Cull after Lesion Diagnosis

For last 12 months

::: panel-tabset

## Non-Infectious Lesion 
:::: panel-tabset

### Graph
```{r}
#| label: fig_cull-noninf

# survival analysis
# km anaylsys

# prep data
cull_data <- lame_data |> 
    filter(lact_number > 0) |>
    filter(date_event >= date_max_pull - months(12)) |> 
    filter(days_to_censor_cull >0) |> 
    group_by(id_animal) |>
    slice_max(order_by = date_event, n = 1, with_ties = FALSE) |>
    ungroup() |>
    mutate(
      lesion = case_when(
        lesion == 1 & status_lesion == "New" ~ "New Lesion",
        lesion == 1 & status_lesion == "Chronic" ~ "Chronic Lesion",
        lesion == 1 & status_lesion == "Repeat" ~ "Repeat Lesion",
        lesion == 0 ~ "No Lesion"),
      lesion =  fct_drop(fct_relevel(lesion, c("No Lesion", 
                                               "New Lesion", 
                                               "Repeat Lesion",
                                               "Chronic Lesion")
      )),
      noninf = case_when(
      noninf == 1 & status_lesion == "New" ~ "New Lesion",
      noninf == 1 & status_lesion == "Chronic" ~ "Chronic Lesion",
      noninf == 1 & status_lesion == "Repeat" ~ "Repeat Lesion",
      noninf == 0 ~ "No Lesion"
    ),
    noninf = fct_drop(fct_relevel(noninf, c("No Lesion", 
                                            "New Lesion", 
                                            "Repeat Lesion",
                                            "Chronic Lesion")
    ))
    )

km_fit <- survfit2(Surv(time = days_to_censor_cull,
                event = culled_last_trim) ~ noninf, 
data = cull_data)

surv_plot <- km_fit |> 
  ggsurvfit(
    type = "risk"
  )+
  add_confidence_interval()+
  add_quantile()+
  scale_ggsurvfit()+
  scale_fill_viridis_d(name = "Non-Infectious Lesion Status")+
  scale_color_viridis_d(name = "Non-Infectious Lesion Status")+
  labs(x = "Days to Culling after Trim",
       y = "Percent of Cows Culled")+
  theme_minimal()+
  theme(legend.position = "bottom")

surv_plot

```

### Risk Table

```{r}
#| label: fig_cull-noninf-table

# times are adjustable

surv_table <- km_fit |>
  tbl_survfit(
    times = c(7, 30, 60, 180),
    label = " ",
    type = "risk",
    label_header = "{time} Days"
  ) %>%
  as_flex_table() %>% # makes formatting and pdf better
  add_header_row(
    top = TRUE,
    values = c(
      "Non-Infectious Lesion Status",
      "% Culled (Confidence Interval) at",
      "",
      "", ""
    )
  ) %>%
  bold(i = 1, bold = TRUE, part = "header") %>% # bolds headers
  bold(i = 2, bold = TRUE, part = "header") %>%
  merge_at(i = 1:2, j = 1, part = "header") %>% # merges 1st row
  merge_at(i = 1, j = 2:5, part = "header") # merges top columns

surv_table
```
::::
:::



<!-- # add DIM stuff -->
<!-- # note doesn't work as 1 herd doens't have non infectious lesions so need a check -->
<!-- Add repeat stuff from VVC here. -->

<!-- ## Time to cull after lesion diagnosis for Non infectious lesions -->

<!-- ```{r} -->
<!-- #| label: survival data -->

<!-- surv_data <- lame_data |>  -->
<!--     filter(lact_number > 0) |> -->
<!--     filter(date_event >= date_max_pull - months(12)) |>  -->
<!--     filter(days_to_censor_cull >0) |>  -->
<!--     group_by(location_event, id_animal) |> -->
<!--     slice_max(order_by = date_event, n = 1, with_ties = FALSE) |> -->
<!--     ungroup() |> -->
<!--     mutate( -->
<!--       lesion = case_when( -->
<!--         lesion == 1 & status_lesion == "New" ~ "New Lesion", -->
<!--         lesion == 1 & status_lesion == "Chronic" ~ "Chronic Lesion", -->
<!--         lesion == 1 & status_lesion == "Repeat" ~ "Repeat Lesion", -->
<!--         lesion == 0 ~ "No Lesion"), -->
<!--       lesion =  fct_drop(fct_relevel(lesion, c("No Lesion",  -->
<!--                                                "New Lesion",  -->
<!--                                                "Repeat Lesion", -->
<!--                                                "Chronic Lesion") -->
<!--       )), -->
<!--       noninf = case_when( -->
<!--       noninf == 1 & status_lesion == "New" ~ "New Lesion", -->
<!--       noninf == 1 & status_lesion == "Chronic" ~ "Chronic Lesion", -->
<!--       noninf == 1 & status_lesion == "Repeat" ~ "Repeat Lesion", -->
<!--       noninf == 0 ~ "No Lesion" -->
<!--     ), -->
<!--     noninf = fct_drop(fct_relevel(noninf, c("No Lesion",  -->
<!--                                             "New Lesion",  -->
<!--                                             "Repeat Lesion", -->
<!--                                             "Chronic Lesion") -->
<!--     )) -->
<!--     ) -->


<!-- ``` -->



<!-- ```{r} -->
<!-- #| label: fig-example_km -->
<!-- #| echo: true -->

<!-- # survival analysis -->
<!-- # km anaylsys -->

<!-- farm1 <- surv_data |>  -->
<!--   filter() -->
<!--   filter(location_event == farm_name[1]) -->


<!-- km_fit <- survfit2(Surv(time = days_to_censor_cull, -->
<!--                 event = culled_last_trim) ~ noninf,  -->
<!-- data = surv_data) -->

<!-- surv_plot <- km_fit |>  -->
<!--   ggsurvfit( -->
<!--     type = "risk" -->
<!--   )+ -->
<!--   add_confidence_interval()+ -->
<!--   add_quantile()+ -->
<!--   scale_ggsurvfit()+ -->
<!--   scale_fill_viridis_d(name = "Non-Infectious Lesion Status")+ -->
<!--   scale_color_viridis_d(name = "Non-Infectious Lesion Status")+ -->
<!--   labs(x = "Days to Culling after Trim", -->
<!--        y = "Percent of Cows Culled")+ -->
<!--   theme_minimal()+ -->
<!--   theme(legend.position = "bottom") -->

<!-- surv_plot -->
<!-- ``` -->

<!-- ```{r} -->
<!-- #| label: fig-example_km_table -->
<!-- #| echo: true -->

<!-- # times are adjustable -->

<!-- surv_table <- km_fit |> -->
<!--   tbl_survfit( -->
<!--     times = c(7, 30, 60, 180), -->
<!--     label = " ", -->
<!--     type = "risk", -->
<!--     label_header = "{time} Days" -->
<!--   ) %>% -->
<!--   as_flex_table() %>% # makes formatting and pdf better -->
<!--   add_header_row( -->
<!--     top = TRUE, -->
<!--     values = c( -->
<!--       "Non-Infectious Lesion Status", -->
<!--       "% Culled (Confidence Interval) at", -->
<!--       "", -->
<!--       "", "" -->
<!--     ) -->
<!--   ) %>% -->
<!--   bold(i = 1, bold = TRUE, part = "header") %>% # bolds headers -->
<!--   bold(i = 2, bold = TRUE, part = "header") %>% -->
<!--   merge_at(i = 1:2, j = 1, part = "header") %>% # merges 1st row -->
<!--   merge_at(i = 1, j = 2:5, part = "header") # merges top columns -->

<!-- surv_table -->


<!-- ``` -->






<!-- ```{r} -->

<!-- source(here::here("functions/fxn_time_to_cull.R")) -->

<!-- library(survival) -->
<!-- library(survminer) -->

<!-- life_colours <- c('Never any lesion' = "#440154ff" , -->
<!--                   'Once' = "#3b528bff", -->
<!--                   'Twice' = "#21908cff", -->
<!--                   '3 or more times' = "#fde725ff" -->
<!--                   ) -->


<!-- years <- "2025" -->

<!-- time_to_cull_non_inf <- lame_cull |> -->
<!--   mutate(year = year(floordate_year)) |> -->
<!--   survival_data(years = years, -->
<!--                 disease = noninf, life_x_dz = life_times_noninf) -->

<!-- km <- time_to_cull_non_inf |> -->
<!--   km_fit(facet_col = farm, facet_row = year) -->

<!-- km -->

<!-- ``` -->

<!-- ### Predicted culling risk at specific times for non-infectious lesions -->


<!-- ```{r} -->
<!-- #| label: surv-table -->

<!-- # iterate over farms -->
<!-- # non infectious -->
<!-- non_inf_table <- map(farms, \(.x) km_fit_table(data = time_to_cull_non_inf, -->
<!--                                      farms = .x) -->
<!--            ) -->

<!-- # label list -->
<!-- names(non_inf_table) <- farms -->

<!-- ``` -->

<!-- Tables with cumulative predicted % risk of cow being culled after a lesion occurence at specific time points. -->

<!-- :::: panel-tabset -->
<!-- ```{r} -->
<!-- #| results: asis -->
<!-- #| label: non_inf_surv -->

<!-- # this creates tab for each farm -->

<!-- iwalk(non_inf_table, ~ { -->
<!--   cat('## ', .y, '\n\n') -->

<!--   # needed as a flextable -->
<!--   cat(knitr::knit_print(.x), '\n\n') -->

<!-- }) -->

<!-- ``` -->
<!-- :::: -->


<!-- ## Other graphing options -->

<!-- -   Time to repeat lesion -->

<!-- -   Time to lameness after a routine trim for healthy cows -->

<!-- -   Recheck compliance -->
